---
title: "p8105 HW6 - Sara Kramer (sk4970)"
output: github_document
---

```{r, include = FALSE,message=FALSE,warning=FALSE}
library(tidyverse)
library(readr)
library(ggplot2)
library(ggridges)
library(viridis)
library(modelr)
library(mgcv)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1
```{r}

```

# Problem 2
```{r}
# importing and cleaning data frame. Includes: creating city, state variable, a binary variable if solved or unsolved, fixing an error with one of the city, states, making age numeric, and focusing on Black and White victims
homicide_df = 
  read_csv("data-homicides-master/homicide-data.csv") %>% 
  janitor::clean_names()
  mutate(city_state = str_c(city, state, sep = ", "),
        resolved = case_when(
        disposition == "Closed without arrest" ~ "unsolved",
        disposition == "Open/No arrest"        ~ "unsolved",
        disposition == "Closed by arrest"      ~ "solved")
        ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa, AL") %>%
  as.numeric("victim_age") %>%
  as.character(disposition) %>%
  select(victim_race = "Black", victim_race = "White")

# glm for baltimore
balt_glm = 
  homicide_df %>%
  filter(city_state = "Baltimore, MD") %>%
  glm(solved ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) 
  
balt_glm %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>%
  select(term, log_OR = estimate, OR, p.value) %>% 
  mutate(conf = confint(OR, level - 0.95)) %>%
  knitr::kable(digits = 3)

# for all cities
city_glm = 
  homicide_df %>%
  nest(data = -city_state) %>%
  mutate(
    models = map(data, ~glm(solved ~ victim_age + victim_sex + victim_race, data =., family = binomial())),
    results = map(models, broom::tidy(conf.int = TRUE)) %>%
    unnest() %>%
    select(city_state, models)
  )
   
```

# Problem 3
```{r}
# importing and cleaning data frame including making necessary variables character variables and removing missing data
birthweight_df = 
  read_csv("./birthweight.csv") %>% 
  janitor::clean_names() %>%
  as.character(babysex) %>%
  as.character(frace) %>%
  as.character(malform) %>%
  as.character(mrace) %>%
  na.omit()

# regression
cv_df %>%
  dplyr::select(starts_with("rmse")) %>%
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_") %>%
  mutate(model = fct_inorder(model)) %>%
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin()
  
```
